version: '3'

networks:
  web:
    external: true

services:
  webchat-app:
    restart: always
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    image: webchat-app/webchat-app:${TAG:-latest}
    volumes:
      - ./.env:/var/www/html/.env
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.webchat-app.entrypoints=https
      - traefik.http.routers.webchat-app.rule=Host(`${TRAEFIK_HOST:-webchat-app.fabioroque.dev}`)
      - traefik.http.routers.webchat-app.service=webchat-app
      - traefik.http.services.webchat-app.loadbalancer.server.port=80
      - traefik.http.routers.webchat-app.tls.certresolver=leresolver
